### ISSUE TITLE
TODO & feature request

### ISSUE THREAD

**Issue by github-young** [HKFoggyU/hkust-thesis#3]
## Please add features you think necessary in this issue.

- [x] ~~*lstlisting* style for other languages: remove or add?~~ Removed.
- [x] signature page: list of TEC names? RPG handbook does not mention this.
    I found that ECE department requires this.
- [x] documentation:
    - [x] README (Pages)
    - [x] mythesis
    - [x] dtx
- [x] bib: Add an option for users to change bib style (ieee/nature/...)
- [ ] ~~Different requirements from departments?~~ Issue welcomed.

**Comment by zybbigpy** [comment]
- I have some suggestions for documentation. For the Readme page, we just need to provide a brief introduction of this 
project and guide users to the manuals or online docs (so I recommend host an online doc by GitHub pages).
- Another thing, it seems the font size of the thesis title can be larger, and we can choose a more beautiful font by default.

**Comment by github-young** [comment]
> * I have some suggestions for documentation. For the Readme page, we just need to provide a brief introduction of this
>   project and guide users to the manuals or online docs (so I recommend host an online doc by GitHub pages).
> * Another thing, it seems the font size of the thesis title can be larger, and we can choose a more beautiful font by default.

I am working on README and PDF documentations. It is a good idea to host docs on Pages. I can start to work on it after I complete the PDF documentation.

I will have a look at the font size. For font type, I think Times New Roman (on Windows/MacOS) is the most commonly used so I do not want to change default font to another one. But there is, IIRC, a setting allowing users to have full control on customizing the fonts.

**Comment by zybbigpy** [comment]
I can help work on the `Makefile` and online documentation.

**Comment by thorcs1** [comment]
Hi! I really loved your template. I am thinking on using it for my own thesis on Overleaf. I have a request though: Can it be modified to be in B5 instead of A4?
Thank you in advance.

**Comment by github-young** [comment]
> Hi! I really loved your template. I am thinking on using it for my own thesis on Overleaf. I have a request though: Can it be modified to be in B5 instead of A4? Thank you in advance.

Thank you for your love.

If you want to use `b5` instead of `a4`, you can modify the `hkustthesis.cls` file, search for `a4paper` and then replace it with `b5paper`. This is the easiest method for general users to achieve this.

However, I have not tested `b5paper` page size, so I am not sure whether there will be new bugs. Please file issues if any. Thanks.

**Comment by thorcs1** [comment]
> > Hi! I really loved your template. I am thinking on using it for my own thesis on Overleaf. I have a request though: Can it be modified to be in B5 instead of A4? Thank you in advance.
> 
> Thank you for your love.
> 
> If you want to use `b5` instead of `a4`, you can modify the `hkustthesis.cls` file, search for `a4paper` and then replace it with `b5paper`. This is the easiest method for general users to achieve this.
> 
> However, I have not tested `b5paper` page size, so I am not sure whether there will be new bugs. Please file issues if any. Thanks.

Thank you very much for your quick answer. I will try it and test if there is any bug.
